# Generated by Django 2.2 on 2019-04-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movienightevent',
            old_name='data',
            new_name='date',
        ),
    ]
