# Generated by Django 2.2 on 2019-10-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingparameters',
            old_name='initial_email_before',
            new_name='initial_email_after',
        ),
    ]
