# Generated by Django 2.2 on 2019-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0002_auto_20190420_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
