# Generated by Django 2.2 on 2019-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0003_auto_20190420_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='MovieNightEvent',
        ),
        migrations.AddField(
            model_name='movie',
            name='MovieNightEvent',
            field=models.ManyToManyField(to='userhandling.MovieNightEvent'),
        ),
    ]
