# Generated by Django 2.2.4 on 2019-11-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0003_auto_20191030_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_invitor',
            field=models.BooleanField(default=False),
        ),
    ]
