# Generated by Django 2.2.4 on 2019-11-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0004_profile_is_invitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
