# Generated by Django 2.2.4 on 2019-11-05 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhandling', '0005_profile_invitation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='loc_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='invitation_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_invitor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.CreateModel(
            name='location_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('registration_complete', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('HO', 'Host'), ('AM', 'Ambassador'), ('GU', 'Guest')], default='GU', max_length=2)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhandling.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
