# Generated by Django 2.2 on 2019-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0005_auto_20190420_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='MovieNightEvent',
        ),
        migrations.AddField(
            model_name='movienightevent',
            name='MovieList',
            field=models.ManyToManyField(blank=True, to='userhandling.Movie'),
        ),
    ]
