# Generated by Django 2.2 on 2019-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0006_auto_20190420_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(max_length=2000),
        ),
    ]
