# Generated by Django 2.2.4 on 2019-11-05 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhandling', '0006_auto_20191104_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location_permission',
            new_name='LocationPermission',
        ),
    ]
