# Generated by Django 2.2.4 on 2019-11-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0007_auto_20191104_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpermission',
            name='registration_complete',
        ),
    ]
