# Generated by Django 2.2 on 2019-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0009_auto_20190422_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset_key', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
