# Generated by Django 2.2 on 2019-05-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0011_auto_20190507_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='reset_used',
            field=models.BooleanField(default=False),
        ),
    ]
