# Generated by Django 2.2 on 2019-06-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0012_passwordreset_reset_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbID',
            new_name='IMDBID',
        ),
        migrations.AddField(
            model_name='movie',
            name='amazon_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='netflix_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='on_amazon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='on_netflix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdbID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
