# Generated by Django 2.2.4 on 2019-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0013_auto_20191123_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpermission',
            name='rev_access_hash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpermission',
            name='revoced_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationpermission',
            name='role',
            field=models.CharField(choices=[('HO', 'Host'), ('AM', 'Ambassador'), ('GU', 'Guest')], default='GU', max_length=2),
        ),
    ]
