# Generated by Django 2.2 on 2019-06-03 21:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0013_auto_20190603_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienightevent',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
