# Generated by Django 2.2 on 2019-06-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0013_auto_20190603_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienightevent',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
