# Generated by Django 2.2.4 on 2019-11-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0014_auto_20191125_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpermission',
            name='rev_access_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
