# Generated by Django 2.2.8 on 2019-12-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0016_auto_20191126_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmdbID',
            new_name='tmdbid',
        ),
    ]
