# Generated by Django 2.2 on 2019-06-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0016_auto_20190605_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienightevent',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
