# Generated by Django 2.2 on 2019-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0018_auto_20190605_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienightevent',
            name='description',
            field=models.TextField(max_length=1000000),
        ),
    ]
