# Generated by Django 2.2 on 2019-06-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0019_auto_20190605_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienightevent',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
