# Generated by Django 2.2 on 2019-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0020_auto_20190605_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienightevent',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
