# Generated by Django 2.2 on 2019-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0021_auto_20190605_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='IMDBID',
        ),
        migrations.AddField(
            model_name='movie',
            name='posterpath',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='trailerlink',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
