# Generated by Django 2.2 on 2019-06-16 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhandling', '0022_auto_20190608_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienightevent',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VoteHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votecount', models.IntegerField(default=0)),
                ('VoterList', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userhandling.Movie')),
                ('movienight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userhandling.MovieNightEvent')),
            ],
        ),
    ]
