# Generated by Django 2.2 on 2019-06-17 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhandling', '0023_auto_20190616_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienightevent',
            name='AttendenceList',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movienightevent',
            name='MaxAttendence',
            field=models.IntegerField(default=25),
        ),
    ]
