# Generated by Django 2.2 on 2019-06-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0027_votepreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepreference',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userhandling.Movie'),
        ),
        migrations.AlterField(
            model_name='votepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
