# Generated by Django 2.2 on 2019-06-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0028_auto_20190618_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepreference',
            name='movienight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userhandling.MovieNightEvent'),
        ),
    ]
