# Generated by Django 2.2 on 2019-06-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0032_movienightevent_isdeactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepreference',
            name='movienight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhandling.MovieNightEvent'),
        ),
    ]
