# Generated by Django 2.2 on 2019-06-30 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhandling', '0033_auto_20190621_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepreference',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhandling.Movie'),
        ),
        migrations.AlterField(
            model_name='votepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Toping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toping', models.CharField(max_length=300)),
                ('movienight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhandling.MovieNightEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
