# Generated by Django 2.2 on 2019-07-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0035_auto_20190630_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovienightTopping',
        ),
    ]
