# Generated by Django 2.2 on 2019-07-03 11:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('userhandling', '0037_movienighttopping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toping',
            new_name='Topping',
        ),
        migrations.RenameField(
            model_name='movienighttopping',
            old_name='toping',
            new_name='topping',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='toping',
            new_name='topping',
        ),
    ]
