# Generated by Django 2.2 on 2019-07-20 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0038_auto_20190703_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienighttopping',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 20, 12, 27, 16, 102947, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movienighttopping',
            name='movienight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserToppings', to='userhandling.MovieNightEvent'),
        ),
    ]
