# Generated by Django 2.2 on 2019-08-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0042_profile_email_buffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_buffer',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
