# Generated by Django 2.2 on 2019-10-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0043_auto_20190817_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('cirty', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
