# Generated by Django 2.2 on 2019-10-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0044_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='cirty',
            new_name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='lol', max_length=200),
            preserve_default=False,
        ),
    ]
