# Generated by Django 2.2 on 2019-10-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhandling', '0045_auto_20191026_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienightevent',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userhandling.Location'),
            preserve_default=False,
        ),
    ]
